const api = new URL('/api', window.location.origin).toString().replace(/\/$/, '');
const role = document.body.dataset.role;
const allowedPages = {
  admin:['admin.html'],
  research:['research.html','research-drugs.html','research-interactions.html','research-batch.html'],
  prescriber_review:['prescriber.html'], medication_safety:['pharmacy.html'],
  governance:['governance.html'], portfolio_screening:['pharma.html'], public_information:['medication-information.html']
};
async function sessionGuard(){
  const response=await fetch(`${api}/auth/session`); if(!response.ok)return;
  const session=await response.json();
  if(!session.authentication_enabled)return;
  if(!session.user){window.location.replace('/login.html');return;}
  if(session.user.role!=='admin'&&session.user.role!==role){window.location.replace(session.user.workspace_url);return;}
  document.querySelector('[data-user]').textContent=session.user.email;
}
async function signOut(){await fetch(`${api}/auth/logout`,{method:'POST'});window.location.assign('/login.html')}
async function runPair(event){event.preventDefault();const form=event.currentTarget;const output=form.querySelector('.result');output.textContent='Generating evidence…';const body={smiles_a:form.smiles_a.value.trim(),smiles_b:form.smiles_b.value.trim()};const response=await fetch(`${api}/audit/dossier`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok){output.textContent=data.detail||'Analysis could not be completed.';return}const decision=data.decision||{};const collision=data.metabolic_collision||{};output.innerHTML=`<div class="card"><span class="status ${decision.status?.includes('HIGH')?'high':'low'}">${escapeText(decision.status||data.status)}</span><h3>Evidence summary</h3><p>${escapeText(decision.rationale||decision.recommendation||'No rationale returned.')}</p><table class="table"><tr><th>Mechanistic signal</th><th>Value</th></tr><tr><td>Dominant metabolic pathway</td><td>${escapeText(collision.dominant_cyp||'Not available')}</td></tr><tr><td>Collision index</td><td>${Number(collision.collision_index||0).toFixed(3)}</td></tr></table></div>`}
function escapeText(value){const node=document.createElement('div');node.textContent=String(value??'');return node.innerHTML}
async function registerCompound(event){event.preventDefault();const form=event.currentTarget;const output=form.querySelector('.result');output.textContent='Registering candidate…';const body={name:form.name.value.trim(),external_id:form.external_id.value.trim()||null,smiles:form.smiles.value.trim(),evidence_notes:form.evidence_notes.value.trim()||null};const response=await fetch(`${api}/compounds`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok){output.textContent=data.detail||'Compound could not be registered.';return}output.innerHTML=`<div class="card"><span class="status low">REGISTERED FOR RESEARCH REVIEW</span><h3>${escapeText(data.compound.name)}</h3><p>Record ${data.compound.id} was stored with its canonical structure and provenance notes. It does not alter model training or make a safety claim.</p></div>`;form.reset()}
async function loadCompounds(){const target=document.querySelector('[data-compound-list]');if(!target)return;const response=await fetch(`${api}/compounds`);const data=await response.json().catch(()=>({}));if(!response.ok){target.textContent='Saved research compounds are unavailable.';return}const compounds=data.compounds||[];if(!compounds.length){target.innerHTML='<div class="notice">No compounds have been registered in this deployment.</div>';return}target.innerHTML=`<h2>Recently registered compounds</h2><table class="table"><tr><th>Name</th><th>Identifier</th><th>Structure</th></tr>${compounds.slice(0,10).map(compound=>`<tr><td>${escapeText(compound.name)}</td><td>${escapeText(compound.external_id||'—')}</td><td>${escapeText(compound.smiles)}</td></tr>`).join('')}</table>`}
async function runRegimen(event){event.preventDefault();const form=event.currentTarget;const output=form.querySelector('.result');const rows=form.regimen.value.split(/\r?\n/).map(row=>row.trim()).filter(Boolean);const drugs=rows.map((row,index)=>{const parts=row.split('|');return {name:(parts.length>1?parts[0]:`Drug ${index+1}`).trim(),smiles:(parts.length>1?parts.slice(1).join('|'):parts[0]).trim()}});if(drugs.length<2){output.textContent='Enter at least two structures, one on each line.';return}output.textContent='Generating regimen evidence…';const response=await fetch(`${api}/polypharmacy/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({drugs})});const data=await response.json().catch(()=>({}));if(!response.ok){output.textContent=data.detail||'Regimen evidence could not be generated.';return}const regimen=data.regimen||{};output.innerHTML=`<div class="card"><span class="status ${String(regimen.overall_verdict||'').includes('HIGH')?'high':'low'}">${escapeText(regimen.overall_verdict||'RESEARCH EVIDENCE')}</span><h3>Regimen evidence summary</h3><p>${escapeText(regimen.explanation||'No explanation returned.')}</p><table class="table"><tr><th>Pairs reviewed</th><td>${Number(regimen.pairwise_interactions?.length||0)}</td></tr><tr><th>Maximum collision index</th><td>${Number(regimen.max_collision_index||0).toFixed(3)}</td></tr></table></div>`}
document.querySelectorAll('[data-signout]').forEach(b=>b.addEventListener('click',signOut));document.querySelectorAll('[data-pair-form]').forEach(f=>f.addEventListener('submit',runPair));document.querySelectorAll('[data-compound-form]').forEach(f=>f.addEventListener('submit',registerCompound));document.querySelectorAll('[data-regimen-form]').forEach(f=>f.addEventListener('submit',runRegimen));document.querySelectorAll('a[href="research-batch.html"]').forEach(link=>{if(role==='portfolio_screening')link.href='pharma-campaign.html'});sessionGuard();loadCompounds();
